// @koala-prepend "jquery-1.11.0.min.js"
// @koala-prepend "bootstrap.min.js"
// @koala-prepend "plugins/datatables/jquery.dataTables.min.js"
// @koala-prepend "plugins/datatables/dataTables.bootstrap.js"
// @koala-prepend "plugins/moment/moment.min.js"
// @koala-prepend "plugins/moment/moment-timezone-with-data.min.js"
// @koala-prepend "plugins/moment/moment-timezone-with-data.min.js"
// @koala-prepend "plugins/jsoneditor/jsoneditor.min.js"